# Generated by Django 3.1.2 on 2020-10-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
