# Generated by Django 3.1.2 on 2020-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maskhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskhistory',
            name='id',
        ),
        migrations.AddField(
            model_name='maskhistory',
            name='date',
            field=models.CharField(default=1986, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
